services:
  postgres:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  redis:
    image: redis:latest

  backend:
    image: ${DOCKER_REGISTRY-}banksoftwareapi
    build:
      context: .
      dockerfile: src/BankSoftware.API/Dockerfile

volumes:
   postgres_banksoftware:
   pgadmin:
