x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  postgres:
    container_name: postgres
    environment:
      <<: *db-env
      POSTGRES_DB: banksoftware-db
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_banksoftware:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  backend:
    container_name: backend 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      "ConnectionStrings:BankDbConnection": "Server=postgres;Port=5432;Database=banksoftware-db;User Id=postgres;Password=postgres;"
      "Redis:Host": redis
      "Redis:Port": 6379
      "Redis:Password": redispassword
      "Redis:ExpirationTimeSeconds": 300
    ports:
      - "8000:80"
      - "9000:443"
    depends_on:
      - postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro