services:
  banksoftwaredb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  banksoftware.api:
    image: ${DOCKER_REGISTRY-}banksoftwareapi
    build:
      context: .
      dockerfile: src/BankSoftware.API/Dockerfile

volumes:
   postgres_banksoftware:
   pgadmin:
