version: "3.8"

services:
  postgres:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  backend:
    image: ${DOCKER_REGISTRY-}banksoftwareapi
    build:
      context: .
      dockerfile: src/BankSoftware.API/Dockerfile

  frontend:
    build:
      context: ./frontend/vue.client
      dockerfile: Dockerfile
      args:
        VUE_APP_API_BASE_URL: "https://localhost:9000"

volumes:
   postgres_banksoftware:
   pgadmin:
